### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by benhar-dev** [Mobject-Dev-Team/mobject-graph-webserver#2]
- [ ] Nice handling of unsupported widgets (i.e. node blueprints with no way to display them)
- [ ] Revert path back to slash
- [ ] Fix Struct, Alias, and Enum nodes (their names)
- [ ] Dictionary ordering issue.  For now, make simple OrderedDictionary.
- [ ] Spin up ITcVnImage Display and Literal
- [ ] Drag and drop node
- [ ] Make a vision nodes GausianFilter, BlobDetect
